AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda
Resources:
  PythonTaskAdapterExample:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: task.zip
      Handler: task.handler
      Runtime: python3.10
